# Generated by Django 2.2.3 on 2019-07-29 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocab_builder', '0002_uservocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservocabulary',
            name='input_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab_builder.InputHistory'),
            preserve_default=False,
        ),
    ]
